### ISSUE TITLE
Feature request: Allow custom X-clacks-overhead contents

### ISSUE THREAD

**Issue by nralbers** [nickcernis/GNU-Terry-Pratchett#6]
While we all miss Terry Pratchett, some of us have other loved ones we'd like to memorialise in the overhead of our own sites. The protocol allows for adding additional names in a comma separated list.
Would it be possible to add a setting to add additional names?

As an example, see the headers of The Register (www.theregister.co.uk)
`x-clacks-overhead: GNU Terry Pratchett, Lester Haines`

**Comment by nickcernis** [comment]
Great suggestion, @nralbers!

This is now available with version 0.4.0 (out now).

After you update and refresh your WP admin, you should see a page at Settings → GNU Terry Pratchett where you can extend or replace the default text:

<img width="788" alt="Screenshot 2022-05-07 at 21 54 30" src="https://user-images.githubusercontent.com/647669/167269905-ff676a7f-9645-4cf6-b514-ebaec5b09617.png">
